// <auto-generated />
namespace VoiceTTS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class name2profilename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(name2profilename));
        
        string IMigrationMetadata.Id
        {
            get { return "202106141143485_name2profilename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
